</main>

<footer>



    <div>
        <a href="mailto:sylvain.jnt@gmail.com" class="mailto" id="mailto">sylvain.jnt[@]gmail.com</a>
    </div>

    <div>
        <p><em>Mon site est en permanence en cours de développement, je l'améliore au fur et à mesure de ma progression !</em></p>
    </div>

    <div>
        <p>(c) Juillet 2020 Tous droits réservés</p>
    </div>


</footer>


<script type="text/javascript" src="<?= PATH ?>public/js/driver.js"></script>
<script type="text/javascript" src="<?= PATH ?>public/js/api.js"></script> 

</body>

</html>