<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="<?= PATH ?>public/css/st.css">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <title>sylvain-janot.fr</title>
</head>

<body>
    <header>
        <div>
            <a href="<?= PATH ?>index">Page d'accueil</a>
        </div>
        <div>
            <a href="<?= PATH ?>about">Mon C.V</a>
        </div>
        <div>
            <a href="<?= PATH ?>realisations">Mes réalisations</a>
        </div>
        <div>
            <a href="<?= PATH ?>contact">Contactez moi!</a>
        </div>

    </header>
    <main>